// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRank.proto

#ifndef PROTOBUF_MsgRank_2eproto__INCLUDED
#define PROTOBUF_MsgRank_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "MsgType.pb.h"
// @@protoc_insertion_point(includes)

namespace MsgPB {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MsgRank_2eproto();
void protobuf_AssignDesc_MsgRank_2eproto();
void protobuf_ShutdownFile_MsgRank_2eproto();

class MsgRankData;
class MsgRankC2S;
class MsgRankS2C;

enum RANK_TPY {
  RANK_TPY_NONE = 0,
  RANK_TPY_NOBILITY = 1
};
bool RANK_TPY_IsValid(int value);
const RANK_TPY RANK_TPY_MIN = RANK_TPY_NONE;
const RANK_TPY RANK_TPY_MAX = RANK_TPY_NOBILITY;
const int RANK_TPY_ARRAYSIZE = RANK_TPY_MAX + 1;

const ::google::protobuf::EnumDescriptor* RANK_TPY_descriptor();
inline const ::std::string& RANK_TPY_Name(RANK_TPY value) {
  return ::google::protobuf::internal::NameOfEnum(
    RANK_TPY_descriptor(), value);
}
inline bool RANK_TPY_Parse(
    const ::std::string& name, RANK_TPY* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RANK_TPY>(
    RANK_TPY_descriptor(), name, value);
}
// ===================================================================

class MsgRankData : public ::google::protobuf::Message {
 public:
  MsgRankData();
  virtual ~MsgRankData();

  MsgRankData(const MsgRankData& from);

  inline MsgRankData& operator=(const MsgRankData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRankData& default_instance();

  void Swap(MsgRankData* other);

  // implements Message ----------------------------------------------

  MsgRankData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRankData& from);
  void MergeFrom(const MsgRankData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 iggid = 1;
  inline bool has_iggid() const;
  inline void clear_iggid();
  static const int kIggidFieldNumber = 1;
  inline ::google::protobuf::int64 iggid() const;
  inline void set_iggid(::google::protobuf::int64 value);

  // optional int32 rankIdx = 2;
  inline bool has_rankidx() const;
  inline void clear_rankidx();
  static const int kRankIdxFieldNumber = 2;
  inline ::google::protobuf::int32 rankidx() const;
  inline void set_rankidx(::google::protobuf::int32 value);

  // optional int64 n64Value = 3;
  inline bool has_n64value() const;
  inline void clear_n64value();
  static const int kN64ValueFieldNumber = 3;
  inline ::google::protobuf::int64 n64value() const;
  inline void set_n64value(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgRankData)
 private:
  inline void set_has_iggid();
  inline void clear_has_iggid();
  inline void set_has_rankidx();
  inline void clear_has_rankidx();
  inline void set_has_n64value();
  inline void clear_has_n64value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 iggid_;
  ::google::protobuf::int64 n64value_;
  ::google::protobuf::int32 rankidx_;
  friend void  protobuf_AddDesc_MsgRank_2eproto();
  friend void protobuf_AssignDesc_MsgRank_2eproto();
  friend void protobuf_ShutdownFile_MsgRank_2eproto();

  void InitAsDefaultInstance();
  static MsgRankData* default_instance_;
};
// -------------------------------------------------------------------

class MsgRankC2S : public ::google::protobuf::Message {
 public:
  MsgRankC2S();
  virtual ~MsgRankC2S();

  MsgRankC2S(const MsgRankC2S& from);

  inline MsgRankC2S& operator=(const MsgRankC2S& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRankC2S& default_instance();

  void Swap(MsgRankC2S* other);

  // implements Message ----------------------------------------------

  MsgRankC2S* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRankC2S& from);
  void MergeFrom(const MsgRankC2S& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_C2S];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int64 iggid = 2;
  inline bool has_iggid() const;
  inline void clear_iggid();
  static const int kIggidFieldNumber = 2;
  inline ::google::protobuf::int64 iggid() const;
  inline void set_iggid(::google::protobuf::int64 value);

  // optional .MsgPB.RANK_TPY rankTpy = 3;
  inline bool has_ranktpy() const;
  inline void clear_ranktpy();
  static const int kRankTpyFieldNumber = 3;
  inline ::MsgPB::RANK_TPY ranktpy() const;
  inline void set_ranktpy(::MsgPB::RANK_TPY value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgRankC2S)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_iggid();
  inline void clear_has_iggid();
  inline void set_has_ranktpy();
  inline void clear_has_ranktpy();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 iggid_;
  int msgtype_;
  int ranktpy_;
  friend void  protobuf_AddDesc_MsgRank_2eproto();
  friend void protobuf_AssignDesc_MsgRank_2eproto();
  friend void protobuf_ShutdownFile_MsgRank_2eproto();

  void InitAsDefaultInstance();
  static MsgRankC2S* default_instance_;
};
// -------------------------------------------------------------------

class MsgRankS2C : public ::google::protobuf::Message {
 public:
  MsgRankS2C();
  virtual ~MsgRankS2C();

  MsgRankS2C(const MsgRankS2C& from);

  inline MsgRankS2C& operator=(const MsgRankS2C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRankS2C& default_instance();

  void Swap(MsgRankS2C* other);

  // implements Message ----------------------------------------------

  MsgRankS2C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRankS2C& from);
  void MergeFrom(const MsgRankS2C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_S2C];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional .MsgPB.RANK_TPY rankTpy = 2;
  inline bool has_ranktpy() const;
  inline void clear_ranktpy();
  static const int kRankTpyFieldNumber = 2;
  inline ::MsgPB::RANK_TPY ranktpy() const;
  inline void set_ranktpy(::MsgPB::RANK_TPY value);

  // repeated .MsgPB.MsgRankData data = 3;
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::MsgPB::MsgRankData& data(int index) const;
  inline ::MsgPB::MsgRankData* mutable_data(int index);
  inline ::MsgPB::MsgRankData* add_data();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgPB::MsgRankData >&
      data() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgPB::MsgRankData >*
      mutable_data();

  // @@protoc_insertion_point(class_scope:MsgPB.MsgRankS2C)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_ranktpy();
  inline void clear_has_ranktpy();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  int ranktpy_;
  ::google::protobuf::RepeatedPtrField< ::MsgPB::MsgRankData > data_;
  friend void  protobuf_AddDesc_MsgRank_2eproto();
  friend void protobuf_AssignDesc_MsgRank_2eproto();
  friend void protobuf_ShutdownFile_MsgRank_2eproto();

  void InitAsDefaultInstance();
  static MsgRankS2C* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgRankData

// optional int64 iggid = 1;
inline bool MsgRankData::has_iggid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRankData::set_has_iggid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRankData::clear_has_iggid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRankData::clear_iggid() {
  iggid_ = GOOGLE_LONGLONG(0);
  clear_has_iggid();
}
inline ::google::protobuf::int64 MsgRankData::iggid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankData.iggid)
  return iggid_;
}
inline void MsgRankData::set_iggid(::google::protobuf::int64 value) {
  set_has_iggid();
  iggid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgRankData.iggid)
}

// optional int32 rankIdx = 2;
inline bool MsgRankData::has_rankidx() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRankData::set_has_rankidx() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRankData::clear_has_rankidx() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRankData::clear_rankidx() {
  rankidx_ = 0;
  clear_has_rankidx();
}
inline ::google::protobuf::int32 MsgRankData::rankidx() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankData.rankIdx)
  return rankidx_;
}
inline void MsgRankData::set_rankidx(::google::protobuf::int32 value) {
  set_has_rankidx();
  rankidx_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgRankData.rankIdx)
}

// optional int64 n64Value = 3;
inline bool MsgRankData::has_n64value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgRankData::set_has_n64value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgRankData::clear_has_n64value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgRankData::clear_n64value() {
  n64value_ = GOOGLE_LONGLONG(0);
  clear_has_n64value();
}
inline ::google::protobuf::int64 MsgRankData::n64value() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankData.n64Value)
  return n64value_;
}
inline void MsgRankData::set_n64value(::google::protobuf::int64 value) {
  set_has_n64value();
  n64value_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgRankData.n64Value)
}

// -------------------------------------------------------------------

// MsgRankC2S

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_C2S];
inline bool MsgRankC2S::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRankC2S::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRankC2S::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRankC2S::clear_msgtype() {
  msgtype_ = 3000;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgRankC2S::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankC2S.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgRankC2S::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgRankC2S.msgType)
}

// optional int64 iggid = 2;
inline bool MsgRankC2S::has_iggid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRankC2S::set_has_iggid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRankC2S::clear_has_iggid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRankC2S::clear_iggid() {
  iggid_ = GOOGLE_LONGLONG(0);
  clear_has_iggid();
}
inline ::google::protobuf::int64 MsgRankC2S::iggid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankC2S.iggid)
  return iggid_;
}
inline void MsgRankC2S::set_iggid(::google::protobuf::int64 value) {
  set_has_iggid();
  iggid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgRankC2S.iggid)
}

// optional .MsgPB.RANK_TPY rankTpy = 3;
inline bool MsgRankC2S::has_ranktpy() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgRankC2S::set_has_ranktpy() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgRankC2S::clear_has_ranktpy() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgRankC2S::clear_ranktpy() {
  ranktpy_ = 0;
  clear_has_ranktpy();
}
inline ::MsgPB::RANK_TPY MsgRankC2S::ranktpy() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankC2S.rankTpy)
  return static_cast< ::MsgPB::RANK_TPY >(ranktpy_);
}
inline void MsgRankC2S::set_ranktpy(::MsgPB::RANK_TPY value) {
  assert(::MsgPB::RANK_TPY_IsValid(value));
  set_has_ranktpy();
  ranktpy_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgRankC2S.rankTpy)
}

// -------------------------------------------------------------------

// MsgRankS2C

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_S2C];
inline bool MsgRankS2C::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRankS2C::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRankS2C::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRankS2C::clear_msgtype() {
  msgtype_ = 3001;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgRankS2C::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankS2C.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgRankS2C::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgRankS2C.msgType)
}

// optional .MsgPB.RANK_TPY rankTpy = 2;
inline bool MsgRankS2C::has_ranktpy() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRankS2C::set_has_ranktpy() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRankS2C::clear_has_ranktpy() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRankS2C::clear_ranktpy() {
  ranktpy_ = 0;
  clear_has_ranktpy();
}
inline ::MsgPB::RANK_TPY MsgRankS2C::ranktpy() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankS2C.rankTpy)
  return static_cast< ::MsgPB::RANK_TPY >(ranktpy_);
}
inline void MsgRankS2C::set_ranktpy(::MsgPB::RANK_TPY value) {
  assert(::MsgPB::RANK_TPY_IsValid(value));
  set_has_ranktpy();
  ranktpy_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgRankS2C.rankTpy)
}

// repeated .MsgPB.MsgRankData data = 3;
inline int MsgRankS2C::data_size() const {
  return data_.size();
}
inline void MsgRankS2C::clear_data() {
  data_.Clear();
}
inline const ::MsgPB::MsgRankData& MsgRankS2C::data(int index) const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgRankS2C.data)
  return data_.Get(index);
}
inline ::MsgPB::MsgRankData* MsgRankS2C::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:MsgPB.MsgRankS2C.data)
  return data_.Mutable(index);
}
inline ::MsgPB::MsgRankData* MsgRankS2C::add_data() {
  // @@protoc_insertion_point(field_add:MsgPB.MsgRankS2C.data)
  return data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgPB::MsgRankData >&
MsgRankS2C::data() const {
  // @@protoc_insertion_point(field_list:MsgPB.MsgRankS2C.data)
  return data_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgPB::MsgRankData >*
MsgRankS2C::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:MsgPB.MsgRankS2C.data)
  return &data_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgPB

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MsgPB::RANK_TPY> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MsgPB::RANK_TPY>() {
  return ::MsgPB::RANK_TPY_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgRank_2eproto__INCLUDED
