// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRank.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MsgRank.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MsgPB {

namespace {

const ::google::protobuf::Descriptor* MsgRankData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgRankData_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgRankC2S_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgRankC2S_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgRankS2C_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgRankS2C_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* RANK_TPY_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_MsgRank_2eproto() {
  protobuf_AddDesc_MsgRank_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MsgRank.proto");
  GOOGLE_CHECK(file != NULL);
  MsgRankData_descriptor_ = file->message_type(0);
  static const int MsgRankData_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankData, iggid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankData, rankidx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankData, n64value_),
  };
  MsgRankData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgRankData_descriptor_,
      MsgRankData::default_instance_,
      MsgRankData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgRankData));
  MsgRankC2S_descriptor_ = file->message_type(1);
  static const int MsgRankC2S_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankC2S, msgtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankC2S, iggid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankC2S, ranktpy_),
  };
  MsgRankC2S_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgRankC2S_descriptor_,
      MsgRankC2S::default_instance_,
      MsgRankC2S_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankC2S, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankC2S, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgRankC2S));
  MsgRankS2C_descriptor_ = file->message_type(2);
  static const int MsgRankS2C_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankS2C, msgtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankS2C, ranktpy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankS2C, data_),
  };
  MsgRankS2C_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgRankS2C_descriptor_,
      MsgRankS2C::default_instance_,
      MsgRankS2C_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankS2C, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgRankS2C, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgRankS2C));
  RANK_TPY_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MsgRank_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgRankData_descriptor_, &MsgRankData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgRankC2S_descriptor_, &MsgRankC2S::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgRankS2C_descriptor_, &MsgRankS2C::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MsgRank_2eproto() {
  delete MsgRankData::default_instance_;
  delete MsgRankData_reflection_;
  delete MsgRankC2S::default_instance_;
  delete MsgRankC2S_reflection_;
  delete MsgRankS2C::default_instance_;
  delete MsgRankS2C_reflection_;
}

void protobuf_AddDesc_MsgRank_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::MsgPB::protobuf_AddDesc_MsgType_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rMsgRank.proto\022\005MsgPB\032\rMsgType.proto\"\?\n"
    "\013MsgRankData\022\r\n\005iggid\030\001 \001(\003\022\017\n\007rankIdx\030\002"
    " \001(\005\022\020\n\010n64Value\030\003 \001(\003\"n\n\nMsgRankC2S\022/\n\007"
    "msgType\030\001 \001(\0162\017.MsgPB.EMsgType:\r_MSG_RAN"
    "K_C2S\022\r\n\005iggid\030\002 \001(\003\022 \n\007rankTpy\030\003 \001(\0162\017."
    "MsgPB.RANK_TPY\"\201\001\n\nMsgRankS2C\022/\n\007msgType"
    "\030\001 \001(\0162\017.MsgPB.EMsgType:\r_MSG_RANK_S2C\022 "
    "\n\007rankTpy\030\002 \001(\0162\017.MsgPB.RANK_TPY\022 \n\004data"
    "\030\003 \003(\0132\022.MsgPB.MsgRankData*4\n\010RANK_TPY\022\021"
    "\n\rRANK_TPY_NONE\020\000\022\025\n\021RANK_TPY_NOBILITY\020\001", 400);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MsgRank.proto", &protobuf_RegisterTypes);
  MsgRankData::default_instance_ = new MsgRankData();
  MsgRankC2S::default_instance_ = new MsgRankC2S();
  MsgRankS2C::default_instance_ = new MsgRankS2C();
  MsgRankData::default_instance_->InitAsDefaultInstance();
  MsgRankC2S::default_instance_->InitAsDefaultInstance();
  MsgRankS2C::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MsgRank_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MsgRank_2eproto {
  StaticDescriptorInitializer_MsgRank_2eproto() {
    protobuf_AddDesc_MsgRank_2eproto();
  }
} static_descriptor_initializer_MsgRank_2eproto_;
const ::google::protobuf::EnumDescriptor* RANK_TPY_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RANK_TPY_descriptor_;
}
bool RANK_TPY_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int MsgRankData::kIggidFieldNumber;
const int MsgRankData::kRankIdxFieldNumber;
const int MsgRankData::kN64ValueFieldNumber;
#endif  // !_MSC_VER

MsgRankData::MsgRankData()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgPB.MsgRankData)
}

void MsgRankData::InitAsDefaultInstance() {
}

MsgRankData::MsgRankData(const MsgRankData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgPB.MsgRankData)
}

void MsgRankData::SharedCtor() {
  _cached_size_ = 0;
  iggid_ = GOOGLE_LONGLONG(0);
  rankidx_ = 0;
  n64value_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgRankData::~MsgRankData() {
  // @@protoc_insertion_point(destructor:MsgPB.MsgRankData)
  SharedDtor();
}

void MsgRankData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgRankData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgRankData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgRankData_descriptor_;
}

const MsgRankData& MsgRankData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MsgRank_2eproto();
  return *default_instance_;
}

MsgRankData* MsgRankData::default_instance_ = NULL;

MsgRankData* MsgRankData::New() const {
  return new MsgRankData;
}

void MsgRankData::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MsgRankData*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(iggid_, rankidx_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgRankData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgPB.MsgRankData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 iggid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &iggid_)));
          set_has_iggid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_rankIdx;
        break;
      }

      // optional int32 rankIdx = 2;
      case 2: {
        if (tag == 16) {
         parse_rankIdx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rankidx_)));
          set_has_rankidx();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_n64Value;
        break;
      }

      // optional int64 n64Value = 3;
      case 3: {
        if (tag == 24) {
         parse_n64Value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &n64value_)));
          set_has_n64value();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgPB.MsgRankData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgPB.MsgRankData)
  return false;
#undef DO_
}

void MsgRankData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgPB.MsgRankData)
  // optional int64 iggid = 1;
  if (has_iggid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->iggid(), output);
  }

  // optional int32 rankIdx = 2;
  if (has_rankidx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->rankidx(), output);
  }

  // optional int64 n64Value = 3;
  if (has_n64value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->n64value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgPB.MsgRankData)
}

::google::protobuf::uint8* MsgRankData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgPB.MsgRankData)
  // optional int64 iggid = 1;
  if (has_iggid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->iggid(), target);
  }

  // optional int32 rankIdx = 2;
  if (has_rankidx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->rankidx(), target);
  }

  // optional int64 n64Value = 3;
  if (has_n64value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->n64value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgPB.MsgRankData)
  return target;
}

int MsgRankData::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int64 iggid = 1;
    if (has_iggid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->iggid());
    }

    // optional int32 rankIdx = 2;
    if (has_rankidx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->rankidx());
    }

    // optional int64 n64Value = 3;
    if (has_n64value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->n64value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgRankData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgRankData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgRankData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgRankData::MergeFrom(const MsgRankData& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_iggid()) {
      set_iggid(from.iggid());
    }
    if (from.has_rankidx()) {
      set_rankidx(from.rankidx());
    }
    if (from.has_n64value()) {
      set_n64value(from.n64value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgRankData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgRankData::CopyFrom(const MsgRankData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgRankData::IsInitialized() const {

  return true;
}

void MsgRankData::Swap(MsgRankData* other) {
  if (other != this) {
    std::swap(iggid_, other->iggid_);
    std::swap(rankidx_, other->rankidx_);
    std::swap(n64value_, other->n64value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgRankData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgRankData_descriptor_;
  metadata.reflection = MsgRankData_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MsgRankC2S::kMsgTypeFieldNumber;
const int MsgRankC2S::kIggidFieldNumber;
const int MsgRankC2S::kRankTpyFieldNumber;
#endif  // !_MSC_VER

MsgRankC2S::MsgRankC2S()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgPB.MsgRankC2S)
}

void MsgRankC2S::InitAsDefaultInstance() {
}

MsgRankC2S::MsgRankC2S(const MsgRankC2S& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgPB.MsgRankC2S)
}

void MsgRankC2S::SharedCtor() {
  _cached_size_ = 0;
  msgtype_ = 3000;
  iggid_ = GOOGLE_LONGLONG(0);
  ranktpy_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgRankC2S::~MsgRankC2S() {
  // @@protoc_insertion_point(destructor:MsgPB.MsgRankC2S)
  SharedDtor();
}

void MsgRankC2S::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgRankC2S::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgRankC2S::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgRankC2S_descriptor_;
}

const MsgRankC2S& MsgRankC2S::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MsgRank_2eproto();
  return *default_instance_;
}

MsgRankC2S* MsgRankC2S::default_instance_ = NULL;

MsgRankC2S* MsgRankC2S::New() const {
  return new MsgRankC2S;
}

void MsgRankC2S::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    msgtype_ = 3000;
    iggid_ = GOOGLE_LONGLONG(0);
    ranktpy_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgRankC2S::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgPB.MsgRankC2S)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_C2S];
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MsgPB::EMsgType_IsValid(value)) {
            set_msgtype(static_cast< ::MsgPB::EMsgType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_iggid;
        break;
      }

      // optional int64 iggid = 2;
      case 2: {
        if (tag == 16) {
         parse_iggid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &iggid_)));
          set_has_iggid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_rankTpy;
        break;
      }

      // optional .MsgPB.RANK_TPY rankTpy = 3;
      case 3: {
        if (tag == 24) {
         parse_rankTpy:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MsgPB::RANK_TPY_IsValid(value)) {
            set_ranktpy(static_cast< ::MsgPB::RANK_TPY >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgPB.MsgRankC2S)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgPB.MsgRankC2S)
  return false;
#undef DO_
}

void MsgRankC2S::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgPB.MsgRankC2S)
  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_C2S];
  if (has_msgtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgtype(), output);
  }

  // optional int64 iggid = 2;
  if (has_iggid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->iggid(), output);
  }

  // optional .MsgPB.RANK_TPY rankTpy = 3;
  if (has_ranktpy()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->ranktpy(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgPB.MsgRankC2S)
}

::google::protobuf::uint8* MsgRankC2S::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgPB.MsgRankC2S)
  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_C2S];
  if (has_msgtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgtype(), target);
  }

  // optional int64 iggid = 2;
  if (has_iggid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->iggid(), target);
  }

  // optional .MsgPB.RANK_TPY rankTpy = 3;
  if (has_ranktpy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->ranktpy(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgPB.MsgRankC2S)
  return target;
}

int MsgRankC2S::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_C2S];
    if (has_msgtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgtype());
    }

    // optional int64 iggid = 2;
    if (has_iggid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->iggid());
    }

    // optional .MsgPB.RANK_TPY rankTpy = 3;
    if (has_ranktpy()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->ranktpy());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgRankC2S::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgRankC2S* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgRankC2S*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgRankC2S::MergeFrom(const MsgRankC2S& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgtype()) {
      set_msgtype(from.msgtype());
    }
    if (from.has_iggid()) {
      set_iggid(from.iggid());
    }
    if (from.has_ranktpy()) {
      set_ranktpy(from.ranktpy());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgRankC2S::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgRankC2S::CopyFrom(const MsgRankC2S& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgRankC2S::IsInitialized() const {

  return true;
}

void MsgRankC2S::Swap(MsgRankC2S* other) {
  if (other != this) {
    std::swap(msgtype_, other->msgtype_);
    std::swap(iggid_, other->iggid_);
    std::swap(ranktpy_, other->ranktpy_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgRankC2S::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgRankC2S_descriptor_;
  metadata.reflection = MsgRankC2S_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MsgRankS2C::kMsgTypeFieldNumber;
const int MsgRankS2C::kRankTpyFieldNumber;
const int MsgRankS2C::kDataFieldNumber;
#endif  // !_MSC_VER

MsgRankS2C::MsgRankS2C()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgPB.MsgRankS2C)
}

void MsgRankS2C::InitAsDefaultInstance() {
}

MsgRankS2C::MsgRankS2C(const MsgRankS2C& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgPB.MsgRankS2C)
}

void MsgRankS2C::SharedCtor() {
  _cached_size_ = 0;
  msgtype_ = 3001;
  ranktpy_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgRankS2C::~MsgRankS2C() {
  // @@protoc_insertion_point(destructor:MsgPB.MsgRankS2C)
  SharedDtor();
}

void MsgRankS2C::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgRankS2C::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgRankS2C::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgRankS2C_descriptor_;
}

const MsgRankS2C& MsgRankS2C::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MsgRank_2eproto();
  return *default_instance_;
}

MsgRankS2C* MsgRankS2C::default_instance_ = NULL;

MsgRankS2C* MsgRankS2C::New() const {
  return new MsgRankS2C;
}

void MsgRankS2C::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    msgtype_ = 3001;
    ranktpy_ = 0;
  }
  data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgRankS2C::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgPB.MsgRankS2C)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_S2C];
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MsgPB::EMsgType_IsValid(value)) {
            set_msgtype(static_cast< ::MsgPB::EMsgType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_rankTpy;
        break;
      }

      // optional .MsgPB.RANK_TPY rankTpy = 2;
      case 2: {
        if (tag == 16) {
         parse_rankTpy:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MsgPB::RANK_TPY_IsValid(value)) {
            set_ranktpy(static_cast< ::MsgPB::RANK_TPY >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_data;
        break;
      }

      // repeated .MsgPB.MsgRankData data = 3;
      case 3: {
        if (tag == 26) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_data;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgPB.MsgRankS2C)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgPB.MsgRankS2C)
  return false;
#undef DO_
}

void MsgRankS2C::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgPB.MsgRankS2C)
  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_S2C];
  if (has_msgtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgtype(), output);
  }

  // optional .MsgPB.RANK_TPY rankTpy = 2;
  if (has_ranktpy()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->ranktpy(), output);
  }

  // repeated .MsgPB.MsgRankData data = 3;
  for (int i = 0; i < this->data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->data(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgPB.MsgRankS2C)
}

::google::protobuf::uint8* MsgRankS2C::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgPB.MsgRankS2C)
  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_S2C];
  if (has_msgtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgtype(), target);
  }

  // optional .MsgPB.RANK_TPY rankTpy = 2;
  if (has_ranktpy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->ranktpy(), target);
  }

  // repeated .MsgPB.MsgRankData data = 3;
  for (int i = 0; i < this->data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->data(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgPB.MsgRankS2C)
  return target;
}

int MsgRankS2C::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_RANK_S2C];
    if (has_msgtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgtype());
    }

    // optional .MsgPB.RANK_TPY rankTpy = 2;
    if (has_ranktpy()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->ranktpy());
    }

  }
  // repeated .MsgPB.MsgRankData data = 3;
  total_size += 1 * this->data_size();
  for (int i = 0; i < this->data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->data(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgRankS2C::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgRankS2C* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgRankS2C*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgRankS2C::MergeFrom(const MsgRankS2C& from) {
  GOOGLE_CHECK_NE(&from, this);
  data_.MergeFrom(from.data_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgtype()) {
      set_msgtype(from.msgtype());
    }
    if (from.has_ranktpy()) {
      set_ranktpy(from.ranktpy());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgRankS2C::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgRankS2C::CopyFrom(const MsgRankS2C& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgRankS2C::IsInitialized() const {

  return true;
}

void MsgRankS2C::Swap(MsgRankS2C* other) {
  if (other != this) {
    std::swap(msgtype_, other->msgtype_);
    std::swap(ranktpy_, other->ranktpy_);
    data_.Swap(&other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgRankS2C::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgRankS2C_descriptor_;
  metadata.reflection = MsgRankS2C_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgPB

// @@protoc_insertion_point(global_scope)
